Us02 card
WildCodeSchool/wns-javaangular-2302-prestapoints pull request #14
Opened 2023-05-24 19:15 UTC by PerrineDeFrance

card by perrine

2023-05-24 21:38 UTC, williambouet requested changes

2023-05-24 21:38 UTC, williambouet commented on front/src/app/app.component.html
> +<app-card></app-card>
ton composant ne doit pas apparaître sur la page d'accueil (tout comme le bouton avec Toto, il va nous falloir le supprimer aussi, mais c'est un autre sujet).
tu peux vérifier ta card avec cette vue, mais il en faut pas la push. 
Donc, à supprimer, nous appellerons le composant au besoin

2023-05-24 21:38 UTC, williambouet commented on front/src/app/app.module.ts
> +  declarations: [AppComponent, DemoComponent, FooterComponent, CardComponent],
du coup il faut le retirer ici aussi, et revenir à l'état d'avant

2023-05-24 21:38 UTC, williambouet commented on front/src/assets/activities/upholstery.jpg
même chose, tu as bien fait d'essayer ton visuel avec une image, mais on ne peut pas sauvegarder celle-ci, donc il ne faut pas la mettre.
En attendant on utilisera les images faker (quand le lien avec le back sera fait)
Aurélien travaille sur la possibilité d'upload une image à la création d'une presta par un user.

2023-05-24 21:38 UTC, williambouet commented on front/src/assets/icons/alarm.svg
bootstrap icon te permet de charger tes icones sans les stocker en local. c'est une bonne chose pour une appli d'avoir en local ses icônes pour diverses raisons. Mais en ce qui nous concerne, ce n'est pas nécessaire. Tu peux supprimer toutes tes icones, tu verras qu'elles seront tout de même sur ta card car tu les appelles avec ta classe bi-bi (bootstrap icon)

2023-05-24 21:38 UTC, williambouet commented on front/src/assets/icons/geo-alt.svg
a suppr comme expliqué au dessus

2023-05-24 21:38 UTC, williambouet commented on front/src/app/shared/components/card/card.component.scss
> Il est quasiment possible de faire un site avec très peu de ligne de css en utilisant bootstrap (parfois aucune).
ici, tu créées des classes qui existent déjà dans bootstrap (bs).
Par exemple, la taille de la font en bs est fs-1 jusqu'à fs-6. Soit du plus grand (fs-1) au plus petit (fs-6), 
tu as la même chose avec les titres (h1 à h6, pour info h6 = fs-6).
Donc tu peux mettre la classe fs-6 sur ton texte (fs-6 = 1rem soit 16px) et/ h6 sur les titles. Si jamais fs-6 est trop gros, on surchargera $font-size-base: 0.8rem; c'est la variable bs qui détermine la base de la font.

> pour le border-radius, tu as en bs rounded-0 à 5, et il existe encore plus costaud pour aller jusqu'à dessiner des cercles.

>pour la bordure, elle est inutile, parce que tu mets une bordure transparente
en bs c'est border-0

>pour le box-shadow, en bs c'est shadow

>il serait aussi interressant de mettre un peu de marge autour de ta card, car lorsqu'elle sera appelée en boucle il ne faudra pas qu'elles soient collées les unes autres, pour cela tu peux mettre la classe bs m-2 (margin).

> pour le title et la category, il est vrai que le gras peut être trop violent, mais bs le gère aussi avec fw (font-weight), pour la catégorie tu peux mettre un fw-bold et le title un fw-semibold par exemple

> quand tu regardes le figma, l'image n'a pas de bordure arrondie, même si les classes de bs le génère seule, tu peux forcer en ajoutant rounded-0, ainsi plus de bordure arrondie. 
 
donc, ton fichier styles ne sert pas, désolé, je te fais tout supprimer :-(

le gros avantage d'utiliser bs est lors de la surcharge, tout le site sera modifié en ne changeant qu'un seul fichier. Sinon, on devra aller dans tous les fichiers styles, ce qui est trop lourd.

2023-05-24 21:38 UTC, williambouet commented on front/src/app/shared/components/card/card.component.html
>Ajouter les class bootstrap selon mon commentaire sur le fichier style.
>je ferai un commentaire complet pour préparer la liaison avec le back

2023-05-24 21:41 UTC, williambouet requested changes

2023-05-24 21:41 UTC, williambouet commented on front/package-lock.json
il faudrait regarder les changements de ce fichier...je crois que ce n'est pas bon signe qu'il soit là avec ses 12196 modifs

2023-05-25 07:08 UTC, PerrineDeFrance commented on front/src/app/app.component.html
> +<app-card></app-card>
comment je fais pour avoir le visuel de ce que je fais alors ?

2023-05-25 07:11 UTC, PerrineDeFrance commented on front/src/assets/activities/upholstery.jpg
temporairement on peut en mettre une pour voir à quoi ça ressemble. ca fera qu'une image à supprimer des assets quand les autres auront validé et mettre le code reliant les fakers quand ce sera fait

2023-05-25 07:12 UTC, PerrineDeFrance commented on front/src/assets/icons/alarm.svg
ok

2023-05-25 07:12 UTC, PerrineDeFrance commented on front/src/app/app.module.ts
> +  declarations: [AppComponent, DemoComponent, FooterComponent, CardComponent],
ok

2023-05-25 07:13 UTC, PerrineDeFrance commented on front/src/assets/icons/geo-alt.svg
ok

2023-05-25 07:16 UTC, PerrineDeFrance commented on front/src/app/shared/components/card/card.component.scss
ok je vais essayer de faire tout ça. En revanche la photo n'a pas de bord arrondi dans le figma.

2023-05-25 07:25 UTC, PerrineDeFrance commented on front/package-lock.json
faudra qu'on voie ensemble, je ne vois pas de quoi tu parles

2023-05-25 11:17 UTC, williambouet commented on front/src/app/app.component.html
> +<app-card></app-card>
tu peux faire pareil, mais au moment de push pour faire ta PR, tu dois retirer ces modifs

2023-05-25 11:20 UTC, williambouet commented on front/src/app/shared/components/card/card.component.scss
je suis d'accord, c'est ce que j'ai noté. Par contre l'image de ta card a les bords arrondis.

2023-05-25 11:20 UTC, williambouet commented on front/package-lock.json
ok

2023-05-25 15:00 UTC, PerrineDeFrance commented on front/src/assets/icons/alarm.svg
done

2023-05-25 15:00 UTC, PerrineDeFrance commented on front/src/assets/activities/upholstery.jpg
done

2023-05-25 15:01 UTC, PerrineDeFrance commented on front/src/assets/icons/geo-alt.svg
done

2023-05-25 15:04 UTC, PerrineDeFrance commented on front/src/app/shared/components/card/card.component.scss
Je suis embrouillée. Luc a créé des variables pour les font size etc. ce que tu veux dire c'est qu'il n'y a pas besoin de variables pour tout ça car boostrap a déjà tout par défaut ?

2023-05-25 15:09 UTC, PerrineDeFrance commented on front/src/app/app.component.html
> +<app-card></app-card>
ok c noté

2023-05-29 09:39 UTC, williambouet approved these changes

2023-05-29 09:45 UTC, williambouet approved these changes

2023-05-29 09:49 UTC, williambouet approved these changes

2023-05-29 10:16 UTC, Lucjaubert approved these changes

2023-05-29 10:16 UTC, merged