Us10 prestation modif dto entity faker
WildCodeSchool/wns-javaangular-2302-prestapoints pull request #18
Opened 2023-05-25 15:48 UTC by Vannou28

2023-05-25 18:31 UTC, williambouet requested changes

2023-05-25 18:31 UTC, williambouet commented on back/src/main/resources/application.properties
ne pas changer stp

2023-05-25 18:31 UTC, williambouet commented on back/src/main/java/fr/mapper/PrestationMapper.java
> +            registrationIds.add(registration.getId());
ne serait il pas plus pratique de prendre directement la liste des registrations plutôt que les id ?

2023-05-25 18:31 UTC, williambouet commented on back/src/main/java/fr/dto/PrestationDto.java
> +    private List<Integer> registration;
registration doit prendre un s, c'est une liste
pourquoi faire une liste d'integer et pas de registration ?

2023-05-25 18:31 UTC, williambouet commented on back/src/main/java/fr/entity/Prestation.java
idem, registration doit prendre un s

2023-05-25 18:31 UTC, williambouet commented on back/src/main/java/fr/entity/Prestation.java
>          this.id = id;
registration avec un s

2023-05-25 18:31 UTC, williambouet commented on back/src/main/java/fr/fixture/Fixtures.java
> +	}
l'indentation est cassée (oui je sais je suis chiant, mais on a eu le même formateur ! donc tu ne seras pas surpis ;-)

2023-05-25 18:31 UTC, williambouet commented on back/src/main/java/fr/fixture/PrestationFixtures.java
> +                prestation.setAddPoint(latitude + ", " +  longitude);
les points ne sont pas des coordonnées mais les points à transformer en bon d'achat, pas de virgule, pas de longitude et latitude

2023-05-25 18:31 UTC, williambouet commented on back/src/main/java/fr/mapper/PrestationMapper.java
> +        prestationDto.setRegistration(registrationIds);
ton setRegistration doit prendre un s suite à la modification précédente

2023-05-26 09:15 UTC, PerrineDeFrance approved these changes

2023-05-26 09:53 UTC, williambouet approved these changes

2023-05-26 09:53 UTC, merged