Us 18 profil
WildCodeSchool/wns-javaangular-2302-prestapoints pull request #34
Opened 2023-07-07 09:36 UTC by JauffritCharly

2023-07-07 10:09 UTC, williambouet requested changes

2023-07-07 10:09 UTC, williambouet commented on back/src/main/java/fr/controller/UserController.java
> +            return new ResponseEntity<>("Modification enregistrée", HttpStatus.OK);
string à mettre en enum, et passer une new ResponseApi dans la ResponseEntity

2023-07-07 10:09 UTC, williambouet commented on back/src/main/java/fr/controller/UserController.java
> +        }
string à mettre en enum, et passer une new ResponseApi dans la ResponseEntity

2023-07-07 10:09 UTC, williambouet commented on back/src/main/java/fr/controller/UserController.java
> +            return new ResponseEntity<>("Avatar mis à jour avec succes", HttpStatus.OK);
string à mettre en enum, et passer une new ResponseApi dans la ResponseEntity

2023-07-07 10:09 UTC, williambouet commented on back/src/main/java/fr/controller/UserController.java
> +        return new ResponseEntity<>("Echec mise à jour Avatar", HttpStatus.OK);
string à mettre en enum, et passer une new ResponseApi dans la ResponseEntity

2023-07-07 10:09 UTC, williambouet commented on back/src/main/java/fr/controller/UserController.java
> +            avatarRepository.save(user.getAvatar());
je crois qu'il est préférable de saveAndFlush plutôt que save, de mémoire le save ne met pas à jour la BD, il y a un risque de perte de données, le flush doit être appelé plus tard pour persister. Autant le faire directement

2023-07-07 10:09 UTC, williambouet commented on back/src/main/java/fr/controller/UserController.java
> +            return ResponseEntity.notFound().build();
je ne sais pas si tu souhaite avertir l'utilisateur ou non si notfound

2023-07-07 10:09 UTC, williambouet commented on back/src/main/java/fr/service/UserService.java
> +        PasswordEncoder passwordEncoder = new BCryptPasswordEncoder();
tu dois Mapper (convertToEntity) ton userDto pour le passer en user et ensuite tu fais ce que tu as faire

2023-07-07 10:09 UTC, williambouet commented on front/src/app/shared/services/localStorage.service.ts
> +    return localStorage.getItem(key);
méthode existante : elle est dans authentication.service méthode getToken

2023-09-14 07:15 UTC, Vannou28 approved these changes

2023-09-14 07:17 UTC, williambouet approved these changes

2023-09-14 07:21 UTC, merged